# Generated by Django 4.0.4 on 2022-04-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productorder_order_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_order',
        ),
        migrations.AddField(
            model_name='order',
            name='product_order',
            field=models.ManyToManyField(null=True, to='product.productorder'),
        ),
    ]
