# Generated by Django 4.0.4 on 2022-04-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_order_product_order_order_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_order',
        ),
        migrations.AddField(
            model_name='order',
            name='individual_product_order',
            field=models.ManyToManyField(null=True, through='product.ProductOrder', to='product.product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order'),
        ),
    ]
