# Generated by Django 4.0.4 on 2022-04-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
